# fle paths
- data:
    raw_kt: data/raw/kt4.0/pantip_cleaned_1.csv
    raw_ws: data/raw/wisesight/wisesight.csv
    raw_ws_ori: data/raw/wisesight/
    raw_dict: data/raw/dict/

    processed: data/processed/


# output folders
- output: output/

