# file paths
- data:
    name: ['kt', 'ws', 'tt'] # available dataset for benchmarking

    # don't touch
    raw_kt: data/raw/kt4.0/pantip_cleaned_1.csv
    raw_ws: data/raw/wisesight/
    raw_tt: data/raw/thaitale/tale_data.csv
    raw_dict: data/raw/dict/

    # datasets that were executed by make_dataset.py
    processed_kt: data/processed/kt.csv
    processed_ws: data/processed/wisesight.csv
    processed_tt: data/processed/thaitale.csv

    

- models: src/models/

# feature config
- feature:
    build_method: ['BOW', 'TFIDF', 'W2V', 'POSBOW', 'POSTFIDF', 'DICTBOW', 'DICTTFIDF', 'ALL']
    selection:
        vi_dim: 1500
        mi_dim: 700
        
# output folders
- output: output/

# temp. output, for rapid testing
- output_scratch: output-scratch/