# file paths
- data:
    name: ['kt', 'ws', 'tt'] # available dataset for benchmarking
    # don't touch
    raw_kt: data/raw/kt4.0/pantip_cleaned_1.csv
    raw_ws: data/raw/wisesight/
    raw_tt: data/raw/thaitale/tale_data.csv
    raw_dict: data/raw/dict/

    # datasets that were executed by make_dataset.py
    processed_kt: data/processed/kt.csv
    processed_ws: data/processed/wisesight.csv
    processed_tt: data/processed/thaitale.csv

    # datasets that already pre-processed and transformed includes:
    # all data for each test representation.
    final_original: data/final/original/ 

    # with feature selection
    final_feature_selection: data/final/feature-selection/

    # train/test split 80/20
    final_train_test: data/final/train-test/

    # repeated 10 random for train/validation/test 60/20/20
    final_repeat_random10: data/final/rep-rand10
    

- models: src/models/

# feature config
- feature:
    build_method: ['BOW', 'TFIDF', 'W2V', 'POSBOW', 'POSTFIDF', 'DICTBOW', 'ALL']
    selection:
        vi_dim: 1500
        mi_dim: 700
        
# output folders
- output: output/

# temp. output, for rapid testing
- output_scratch: output-scratch/