# fle paths
- data:
    name: ['kt', 'ws', 'tt']
    raw_kt_ori: data/raw/kt4.0/pantip_cleaned_1.csv
    raw_kt: data/raw/kt4.0/kt.csv

    raw_ws_ori: data/raw/wisesight/
    raw_ws: data/raw/wisesight/wisesight.csv
    
    raw_tt_ori: data/raw/thaitale/tale_data.csv
    raw_tt: data/raw/thaitale/thaitale.csv
    
    raw_dict: data/raw/dict/

    processed: data/processed/

    final_original: data/final/original/

- models: src/models/

# feature config
- feature:
    build_method: ['BOW', 'TFIDF', 'W2V', 'POSBOW', 'POSTFIDF', 'DICTBOW', 'ALL']
    selection:
        vi_dim: 1500
        mi_dim: 700
        
# output folders
- output: output/